services:
  db:
    container_name: db
    image: mysql
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: BooksAPI
      MYSQL_ROOT_PASSWORD: root
    networks:
      backend:

  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure
    environment:
      - spring.jpa.hibernate.ddl-auto=create-drop
      - spring.datasource.url=jdbc:mysql://db:3306/BooksAPI
      - spring.datasource.username=root
      - spring.datasource.password=root
    networks:
      backend:

networks:
  backend: